// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8raUNCo-4OGkjFi5vFrBcIKYbwmza2h4',
    appId: '1:690313055599:web:e77cb9fc089e1436e1ec9a',
    messagingSenderId: '690313055599',
    projectId: 'unite-3b427',
    authDomain: 'unite-3b427.firebaseapp.com',
    storageBucket: 'unite-3b427.appspot.com',
    measurementId: 'G-L61PX9MTSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTScnJkMjVTlw62bDPk3nmY1hLoVxOpIM',
    appId: '1:690313055599:android:c5d67124a3b3a5cee1ec9a',
    messagingSenderId: '690313055599',
    projectId: 'unite-3b427',
    storageBucket: 'unite-3b427.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkbkDlZzrKHQd9PPVsm9ShZSgwAORI8eM',
    appId: '1:690313055599:ios:e1f514d46eb8d65de1ec9a',
    messagingSenderId: '690313055599',
    projectId: 'unite-3b427',
    storageBucket: 'unite-3b427.appspot.com',
    iosBundleId: 'com.example.unite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkbkDlZzrKHQd9PPVsm9ShZSgwAORI8eM',
    appId: '1:690313055599:ios:e1f514d46eb8d65de1ec9a',
    messagingSenderId: '690313055599',
    projectId: 'unite-3b427',
    storageBucket: 'unite-3b427.appspot.com',
    iosBundleId: 'com.example.unite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8raUNCo-4OGkjFi5vFrBcIKYbwmza2h4',
    appId: '1:690313055599:web:6310d40342029ba2e1ec9a',
    messagingSenderId: '690313055599',
    projectId: 'unite-3b427',
    authDomain: 'unite-3b427.firebaseapp.com',
    storageBucket: 'unite-3b427.appspot.com',
    measurementId: 'G-2T9K2E8ZNR',
  );
}
